export const DEFAULT_SESSION_RESOURCE_KEY = '__default__';

export const DEFAULT_TOOL_PLANE_KEY = DEFAULT_SESSION_RESOURCE_KEY;
export const DEFAULT_BRIDGE_SNAPSHOT_KEY = DEFAULT_SESSION_RESOURCE_KEY;
